# arxivの学問領域の指定
subject: 'cs'

# 検索キーワード
keywords:
        anti spoofing: 5
        anti-spoofing: 5
        3d mask: 5
        face mask: 5
        face recognition: 4
        face detect: 4
        face detector: 4
        face detection: 4
        spoof: 4
        spoofing: 4
        facial landmark: 4
        landmark: 3
        deep fake: 2
        virtual reality: 1
        resnet: 1
        stylegan: 1
        style gan: 1
        anomaly detection: 1
