# arxivの学問領域の指定
subject: 'cs'

# 検索キーワード
keywords:
        resnet: 1
        spoof: 4
        spoofing: 4
        anti spoofing: 5
        facial landmark: 4
        landmark: 3
        virtual reality: 1
        deep fake: 2
        stylegan: 1
        style gan: 1
        3d mask: 5
        face recognition: 4
